---
name: CAM-XML
version: 1.12
author:
  - Clotho Advanced Media Inc., I<cpan@clotho.com>
abstract: Encapsulation of a simple XML data structure
license: perl
requires:
  XML::Parser: 2.27
build_requires:
  Test::More: 0.01
provides:
  CAM::XML:
    file: lib/CAM/XML.pm
    version: 1.12
  CAM::XML::Text:
    file: lib/CAM/XML.pm
    version: 1.12
  CAM::XML::XMLTree:
    file: lib/CAM/XML.pm
    version: 1.12
generated_by: Module::Build version 0.2609
